export const GET_HERO_DATA_DETAILS_REQUEST = "GET_HERO_DATA_DETAILS_REQUEST";
export const GET_HERO_DATA_DETAILS_SUCCESS = "GET_HERO_DATA_DETAILS_SUCCESS";
export const GET_HERO_DATA_DETAILS_FAIL = "GET_HERO_DATA_DETAILS_FAIL";
export const GET_HERO_DATA_DETAILS_RESET = "GET_HERO_DATA_DETAILS_RESET";
